server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

jwt:
  secret: E4D78F2EE2EDFE8317F70A12796753D0BFF575DB77D8D24272E78FD268010E1D
