server:
  port: 9001

spring:
  application:
    name: auth-service

jwt:
  secret: 3MB3MT6N4DGzO29Z9PA9Cwuf3qj2zAoe8PpJrfM3UcYiBUXRSKsJOGZdE7GcFIz61GJChzHundRViX1asZKIMtFL0nWWmrTKOrqUQAA3faHHUH7nFcZjaPyASNHj9bUlKJYjaQ
  expiration: 86400